##
## Copyright (C) 2017-2025 Hanson Robotics
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <https://www.gnu.org/licenses/>.
##
mappings:
  azure: # https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-speech-synthesis-viseme?pivots=programming-language-python#map-phonemes-to-visemes
    A-I: ['4', '1', '2', '3', '11', '9']
    C-D-G-K-N-S-TH: ['17', '15', '16']
    E: ['6', '5', '19', '20', '12']
    F-V: ['18']
    L: ['14']
    M: ['21', ]
    O: ['8', '10']
    Q-W: ['7']
    Sil: ['0']
    U: ['13']
  acapela:
    A-I: [4, 1, 2, 3, 11, 9]
    C-D-G-K-N-S-TH: [17, 15, 16]
    E: [6, 5, 19, 20, 12]
    F-V: [18]
    L: [14]
    M: [21]
    O: [8, 10]
    Q-W: [7]
    Sil: [0]
    U: [13]
  polly:
    A-I: [a, '@', E]
    C-D-G-K-N-S-TH: [k, s, S, T]
    E: [e, t, i]
    F-V: [f]
    L: [l, r]
    M: [p, B]
    O: [O]
    Q-W: [w]
    Sil: [sil, ""]
    U: [u, J, o]
params:
  polly:
    A-I: {duration: 1.2, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    C-D-G-K-N-S-TH: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    E: {duration: 1.2, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    F-V: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    L: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    M: {duration: 1.0, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    O: {duration: 1.2, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    Q-W: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    Sil: {duration: 1.0, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    U: {duration: 1.2, magnitude: 0.99, rampin: 0.3, rampout: 0.2}
  azure:
    A-I: {duration: 2.0, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    C-D-G-K-N-S-TH: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    E: {duration: 1.8, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    F-V: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    L: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    M: {duration: 1.0, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    O: {duration: 1.8, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    Q-W: {duration: 1.5, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    Sil: {duration: 1.0, magnitude: 0.99, rampin: 0.2, rampout: 0.2}
    U: {duration: 1.8, magnitude: 0.99, rampin: 0.3, rampout: 0.2}
