# Read the Docs configuration file
# Template Copyright (c) 2010-2024 Read the Docs, Inc & contributors
# MIT License - https://github.com/readthedocs/readthedocs.org/blob/main/LICENSE
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
